[package]
name = "strict_types"
description = "Strict types: confined generalized algebraic data types (GADT)"
version = "1.5.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@ubideco.org>"]
homepage = "https://strict-types.org"
license = "Apache-2.0"
keywords = ["encoding", "strict-encoding", "aluvm", "ubideco", "gadt"]
categories = ["compilers", "parser-implementations", "mathematics", "science", "data-structures"]
edition = "2021"
rust-version = "1.67.0"
readme = "README.md"
exclude = [".github"]

[[bin]]
name = "std-stl"
required-features = ["base64"]

[[bin]]
name = "strict-stl"
required-features = ["base64"]

[[test]]
name = "reflect"
required-features = ["base64"]

[dependencies]
amplify = { version = "4.0.0", features = ["apfloat"] }
strict_encoding = { version = "2.5.0", features = ["derive", "float"] }
indexmap = "1.9.2"
baid58 = "0.4.0"
half = "2.2.0"
sha2 = "0.10.6"
base64 = { version = "0.21.0", optional = true }
serde_crate = { package = "serde", version = "1", optional = true }
serde_with = { version = "2", optional = true }
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.9", optional = true }
toml = { version = "0.7.2", optional = true }

[features]
default = []
all = ["serde", "base64"]
serde = [
    "serde_crate", "serde_with",
    "serde_json", "serde_yaml", "toml",
    "amplify/serde", "strict_encoding/serde"
]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
