[package]
name = "stens"
description = "Strict encoding schema"
version = "0.9.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@protonmail.ch>"]
license = "MIT"
keywords = ["encoding", "strict-encoding", "aluvm"]
categories = ["data-structures", "parser-implementations"]
edition = "2021"
rust-version = "1.60.0"
readme = "README.md"
exclude = [".github", "contrib"]

[dependencies]
amplify = "4.0.0-beta.3"
amplify_derive = "4.0.0-alpha.1" # TODO Remove after WrapperMut re-export bugfix in amplify
confined_encoding = "0.9.0-alpha.5"
