[package]
name = "stens"
description = "Strict encoding schema library"
version = "0.9.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
license = "MIT"
keywords = ["encoding", "internet2", "web4", "aluvm", "lnpbp"]
categories = ["data-structures", "parser-implementations", "web-programming"]
edition = "2021"
rust-version = "1.59.0"
readme = "README.md"
exclude = [".github", "Dockerfile", ".dockerignore", "contrib", "doc", "shell"]

[dependencies]
amplify = "4.0.0-beta.3"
amplify_derive = "4.0.0-alpha.1" # TODO Remove after WrapperMut re-export bugfix in amplify
confined_encoding = "0.9.0-alpha.5"
serde_crate = { package = "serde", version = "1", optional = true }
serde_with = { version = "2", optional = true }
serde_yaml = { version = "0.9", optional = true }

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "serde_with", "serde_yaml", "amplify/serde"]
