[package]
name = "strict_types"
description = "Strict types: confined generalized algebraic data types (GADT)"
version = "1.0.0-beta.2"
authors = ["Dr. Maxim Orlovsky <orlovsky@ubideco.org>"]
homepage = "https://strict-types.org"
license = "Apache-2.0"
keywords = ["encoding", "strict-encoding", "aluvm", "ubideco", "gadt"]
categories = ["compilers", "parser-implementations", "mathematics", "science", "data-structures"]
edition = "2021"
rust-version = "1.66.0"
readme = "README.md"
exclude = [".github"]

[dependencies]
amplify = { version = "4.0.0-beta.9", features = ["apfloat"] }
strict_encoding = { version = "2.0.0-beta.3", features = ["derive", "float"] }
baid58 = "0.1.0"
half = "2.1.0"
blake3 = "1.3.3"
serde_crate = { package = "serde", version = "1", optional = true }
serde_with = { version = "2", optional = true }
serde_yaml = { version = "0.9", optional = true }

[dev-dependencies]
base64 = "0.21.0"

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "serde_with", "serde_yaml", "amplify/serde", "strict_encoding/serde"]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[patch.crates-io]
strict_encoding = { git = "https://github.com/strict-types/strict-encoding" }
