[package]
name = "stens"
description = "Strict encoding schema"
version = "1.0.0-beta.1"
authors = ["Dr. Maxim Orlovsky <orlovsky@ubideco.org>"]
license = "Apache-2.0"
keywords = ["encoding", "strict-encoding", "aluvm"]
categories = ["data-structures", "parser-implementations"]
edition = "2021"
rust-version = "1.60.0"
readme = "README.md"
exclude = [".github", "contrib"]

[dependencies]
amplify = { version = "4.0.0-beta.6", features = ["apfloat"] }
half = "2.1.0"
serde_crate = { package = "serde", version = "1", optional = true }
serde_with = { version = "2", optional = true }
serde_yaml = { version = "0.9", optional = true }

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "serde_with", "serde_yaml", "amplify/serde"]
