[package]
name = "stens"
description = "Strict encoding schema library"
version = "0.9.0-rc.1"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
license = "MIT"
keywords = ["encoding", "internet2", "web4", "aluvm", "lnpbp"]
categories = ["data-structures", "parser-implementations", "web-programming"]
edition = "2021"
rust-version = "1.59.0"
readme = "README.md"
exclude = [".github", "Dockerfile", ".dockerignore", "contrib", "doc", "shell"]

[dependencies]
amplify = "3.13.0"
strict_encoding = { version = "0.9.0-rc.1", default-features = false, features = ["derive"] }
serde_crate = { package = "serde", version = "1", optional = true }
serde_with = { version = "1.14", optional = true }
serde_yaml = { version = "0.9", optional = true }

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "serde_with", "serde_yaml"]
